In [7]:
import numpy as np 
w=np.array([[1,2],[1,2]])
x=w.tolist()
print(x)


[[1 2]
 [1 2]]
[[1, 2], [1, 2]]


In [18]:
m=np.random.randint(0, 10, size=(4,4))
print(m)
x=0
for i in range (len(m)):
    x+=m[i,i]
m = np.trace(m)
print("The manual sum is: ",x)
print("The trace Sum is: ", m)

[[3 3 8 6]
 [0 7 9 6]
 [5 0 5 1]
 [9 2 7 2]]
The manual sum is:  17
The trace Sum is:  17


In [29]:
from random import randint
m=np.random.randint(0, 10, size=(4,4))
x=randint(0,5)
l=[]
for i in range (len(m)):
    for j in range (len(m)):
        if (m[i,j]>x):
            l.append(m[i,j])
print("The array is: \n",m,"\nThe number is: ",x)
print("The numbers bigger than",x,':\n',l)

The array is: 
 [[5 0 3 0]
 [9 9 4 2]
 [0 4 4 1]
 [4 0 6 0]] 
The number is:  3
The numbers bigger than 3 :
 [5, 9, 9, 4, 4, 4, 4, 6]


In [37]:
A=np.random.randint(0, 10, size=(2,2))
B=np.random.randint(0, 10, size=(2,2))
x=0
for i in range (len(A)):
    for j in range (len(A)):
        x+=A[i,j]+B[i,j]
print("A: \n",A,"\nB: \n",B)
print(x)

A: 
 [[8 7]
 [3 4]] 
B: 
 [[7 0]
 [9 1]]
39


In [89]:
m=np.random.randint(0, 10, size=(4,4))
Rsum=m.sum(axis=1)
Rmean=m.mean(axis=1)
print("The Sum of each row: ",Rsum,"\nThe mean of each row: ",Rmean)
l=[]
for i in range (len(Rsum)):
    x=Rsum[i]-Rmean[i]
    l.append(x)
print(l)
    

The Sum of each row:  [27 18 14 19] 
The mean of each row:  [6.75 4.5  3.5  4.75]
[20.25, 13.5, 10.5, 14.25]
